apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kato-bot.name" . }}-clusters
  labels:
    {{- include "kato-bot.labels" . | nindent 4 }}
data:
  clusters.yaml: |
    clusters:
    {{- range .Values.clusters }}
      - name: {{ .name | quote }}
        url: {{ .url | quote }}
        {{- if .label }}
        label: {{ .label | quote }}
        {{- end }}
        {{- if .insecureSkipVerify }}
        insecureSkipVerify: true
        {{- end }}
    {{- end }}
