apiVersion: v1
entries:
  kato-bot:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2026-06-17T13:39:09.81656+07:00"
    description: Lark chat adapter for kato troubleshooting flows
    digest: 824eb6136b4740a120280ab5e67abbadeb785db457800d4da5e46322d96d6e56
    name: kato-bot
    type: application
    urls:
    - kato-bot-0.1.0.tgz
    version: 0.1.0
generated: "2026-06-17T13:39:09.816178+07:00"
